import "server-only";
import { createSupabaseServiceClient } from "@/lib/supabase/service";
import { logServerError } from "@/lib/observability/request-id";
import { signPrintToken } from "@/lib/pdf/print-token";
import { buildPrintUrl } from "@/lib/pdf/print-origin";
import { generateManualPdf } from "@/lib/pdf/generate";
import {
  pdfArtifactStorageKey,
  uploadPdfArtifact,
  downloadPdfArtifact,
  sha256Hex,
} from "@/lib/pdf/artifact-storage";
import { resolvePublishedSnapshotRef } from "@/lib/publication/get-public-manual";

/**
 * Phase 7 slice 4B — WRITE side: generate the PDF for one immutable published snapshot exactly
 * ONCE and store it as an immutable artifact.
 *
 * The distributed generation lock lives in Postgres (`claim_pdf_artifact_generation`): two callers
 * for the same snapshot serialise on a `FOR UPDATE` row lock, so at most one ever launches
 * Chromium; the other sees `in_progress`. This module is only ever invoked from trusted server
 * code (the post-publish step and the ADMIN retry action) — never from `GET /pdf`.
 */

/** Strip anything that could be a secret / token / URL, keep it short — stored in `failure_message`. */
function sanitizeFailure(err: unknown): string {
  let s = (err instanceof Error ? err.message : String(err ?? "")).split("\n")[0] ?? "";
  s = s.replace(/https?:\/\/\S+/gi, "<url>");
  s = s.replace(/[A-Za-z0-9_-]{24,}/g, "<redacted>"); // base64url / hex / jwt-ish runs
  return s.slice(0, 200) || "generation error";
}

export type EnsureResult =
  | { ok: false; reason: "not_found" }
  | { ok: true; snapshotId: string; status: string };

/** Idempotently create the PENDING artifact row for a published snapshot. No Chromium. */
export async function ensurePublishedPdfArtifact(slug: string, version: string): Promise<EnsureResult> {
  const ref = await resolvePublishedSnapshotRef(slug, version);
  if (!ref) return { ok: false, reason: "not_found" };

  const svc = createSupabaseServiceClient();
  const { data, error } = await svc.rpc("ensure_pdf_artifact", {
    p_published_snapshot_id: ref.publishedSnapshotId,
  });
  if (error) {
    await logServerError("pdf-artifact", "ensure failed", { slug, version, code: error.code });
    return { ok: false, reason: "not_found" };
  }
  return { ok: true, snapshotId: ref.publishedSnapshotId, status: (data as { status: string }).status };
}

export type GenerateResult =
  | { outcome: "not_found" }
  | { outcome: "ready" }
  | { outcome: "in_progress" }
  | { outcome: "generated"; sha256: string; byteSize: number; pageCount: number | null }
  | { outcome: "failed"; message: string };

/**
 * Ensure a READY artifact exists for `slug`/`version`, generating it once under the DB lock if
 * needed. Safe to call concurrently — only the claim winner runs Chromium.
 */
export async function generatePublishedPdfArtifact(
  slug: string,
  version: string,
): Promise<GenerateResult> {
  const ref = await resolvePublishedSnapshotRef(slug, version);
  if (!ref) return { outcome: "not_found" };

  const svc = createSupabaseServiceClient();
  const { data: claim, error: claimErr } = await svc.rpc("claim_pdf_artifact_generation", {
    p_published_snapshot_id: ref.publishedSnapshotId,
    p_lease_seconds: 300,
  });
  if (claimErr) {
    await logServerError("pdf-artifact", "claim failed", { slug, version, code: claimErr.code });
    return { outcome: "failed", message: "claim failed" };
  }

  const c = claim as {
    outcome: "ready" | "in_progress" | "claimed";
    leaseToken?: string;
    snapshotContentHash?: string;
    artifactVersion?: number;
  };
  if (c.outcome === "ready") return { outcome: "ready" };
  if (c.outcome === "in_progress") return { outcome: "in_progress" };

  const leaseToken = c.leaseToken!;
  const contentHash = c.snapshotContentHash!;
  const artifactVersion = c.artifactVersion ?? 1;

  try {
    const { bytes, pageCountHint } = await generateManualPdf({
      printUrl: buildPrintUrl(slug, version),
      printToken: signPrintToken(slug, version),
      slug,
      version: ref.publicVersion,
      publishedAt: ref.publishedAt,
      bypassSecret: process.env.VERCEL_AUTOMATION_BYPASS_SECRET || undefined,
    });

    if (bytes.subarray(0, 5).toString("latin1") !== "%PDF-" || !bytes.includes(Buffer.from("EOF"))) {
      throw new Error("generated bytes are not a well-formed PDF");
    }

    const sha256 = sha256Hex(bytes);
    const byteSize = bytes.byteLength;
    const storageKey = pdfArtifactStorageKey(contentHash, artifactVersion);

    await uploadPdfArtifact(storageKey, bytes);

    // read-back verification — the stored object must be byte-identical to what we generated
    const roundTrip = await downloadPdfArtifact(storageKey);
    if (!roundTrip || roundTrip.byteLength !== byteSize || sha256Hex(roundTrip) !== sha256) {
      throw new Error("stored artifact failed read-back verification");
    }

    const { error: completeErr } = await svc.rpc("complete_pdf_artifact_generation", {
      p_published_snapshot_id: ref.publishedSnapshotId,
      p_lease_token: leaseToken,
      p_snapshot_content_hash: contentHash,
      p_storage_key: storageKey,
      p_pdf_sha256: sha256,
      p_byte_size: byteSize,
      p_page_count: pageCountHint,
    });
    if (completeErr) throw new Error(`complete rpc: ${completeErr.message}`);

    return { outcome: "generated", sha256, byteSize, pageCount: pageCountHint };
  } catch (e) {
    const message = sanitizeFailure(e);
    await svc
      .rpc("fail_pdf_artifact_generation", {
        p_published_snapshot_id: ref.publishedSnapshotId,
        p_lease_token: leaseToken,
        p_failure_code: "generation_error",
        p_failure_message: message,
      })
      .then(({ error }) => {
        if (error) return logServerError("pdf-artifact", "fail rpc errored", { slug, version, code: error.code });
      });
    await logServerError("pdf-artifact", "generation failed", { slug, version, msg: message });
    return { outcome: "failed", message };
  }
}
